const IMAGES = {
    LOAD_IMAGES: 'LOAD_IMAGES',
    LOAD_IMAGES_SUCCESS: 'LOAD_IMAGES_SUCCESS',
    LOAD_IMAGES_FAIL: 'LOAD_IMAGES_FAIL'
};

const STATS = {
    LOAD_IMAGES_STATS: 'LOAD_IMAGES_STATS',
    LOAD_IMAGES_STATS_SUCCESS: 'LOAD_IMAGES_STATS_SUCCESS',
    LOAD_IMAGES_STATS_FAIL: 'LOAD_IMAGES_STATS_FAIL'
};

export { IMAGES, STATS };